#Análise de Microdados do ENEM

In [1]:
import pandas as pd
import matplotlib

In [2]:
microdadosEnem = pd.read_csv('MICRODADOS_ENEM_2019.csv', sep=';', encoding='ISO-8859-1')

In [3]:
microdadosEnem.head()

,NU_INSCRICAO,NU_ANO,CO_MUNICIPIO_RESIDENCIA,NO_MUNICIPIO_RESIDENCIA,CO_UF_RESIDENCIA,SG_UF_RESIDENCIA,NU_IDADE,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,...,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025
0,190001595656,2019,3552205,Sorocaba,35,SP,36.0,M,1,3,...,A,A,A,A,A,A,C,A,C,B
1,190001421546,2019,2910800,Feira de Santana,29,BA,23.0,M,1,1,...,A,A,A,B,A,A,E,A,A,B
2,190001133210,2019,2304400,Fortaleza,23,CE,39.0,F,1,3,...,A,A,A,B,A,A,C,A,A,B
3,190001199383,2019,1721000,Palmas,17,TO,25.0,F,1,1,...,A,A,A,C,A,B,D,A,B,B
4,190001237802,2019,3118601,Contagem,31,MG,22.0,F,1,1,...,B,A,A,B,A,A,C,B,B,B

In [4]:
microdadosEnem

,NU_INSCRICAO,NU_ANO,CO_MUNICIPIO_RESIDENCIA,NO_MUNICIPIO_RESIDENCIA,CO_UF_RESIDENCIA,SG_UF_RESIDENCIA,NU_IDADE,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,...,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025
0,190001595656,2019,3552205,Sorocaba,35,SP,36.0,M,1,3,...,A,A,A,A,A,A,C,A,C,B
1,190001421546,2019,2910800,Feira de Santana,29,BA,23.0,M,1,1,...,A,A,A,B,A,A,E,A,A,B
2,190001133210,2019,2304400,Fortaleza,23,CE,39.0,F,1,3,...,A,A,A,B,A,A,C,A,A,B
3,190001199383,2019,1721000,Palmas,17,TO,25.0,F,1,1,...,A,A,A,C,A,B,D,A,B,B
4,190001237802,2019,3118601,Contagem,31,MG,22.0,F,1,1,...,B,A,A,B,A,A,C,B,B,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5095265,190006074437,2019,5300108,Brasília,53,DF,41.0,F,4,3,...,B,A,A,B,A,A,B,B,A,B
5095266,190005429225,2019,1302603,Manaus,13,AM,20.0,M,1,3,...,A,A,A,B,B,A,E,A,A,B
5095267,190006087652,2019,4302105,Bento Gonçalves,43,RS,21.0,M,0,0,...,A,A,A,B,A,A,C,B,B,B
5095268,190006087653,2019,4302105,Bento Gonçalves,43,RS,22.0,M,0,0,...,B,A,A,C,B,B,A,A,A,B
5095269,190006087654,2019,4302105,Bento Gonçalves,43,RS,21.0,F,0,0,...,A,A,A,B,A,A,B,B,B,B

In [5]:
microdadosEnem.columns.values

array(['NU_INSCRICAO', 'NU_ANO', 'CO_MUNICIPIO_RESIDENCIA',
       'NO_MUNICIPIO_RESIDENCIA', 'CO_UF_RESIDENCIA', 'SG_UF_RESIDENCIA',
       'NU_IDADE', 'TP_SEXO', 'TP_ESTADO_CIVIL', 'TP_COR_RACA',
       'TP_NACIONALIDADE', 'CO_MUNICIPIO_NASCIMENTO',
       'NO_MUNICIPIO_NASCIMENTO', 'CO_UF_NASCIMENTO', 'SG_UF_NASCIMENTO',
       'TP_ST_CONCLUSAO', 'TP_ANO_CONCLUIU', 'TP_ESCOLA', 'TP_ENSINO',
       'IN_TREINEIRO', 'CO_ESCOLA', 'CO_MUNICIPIO_ESC',
       'NO_MUNICIPIO_ESC', 'CO_UF_ESC', 'SG_UF_ESC',
       'TP_DEPENDENCIA_ADM_ESC', 'TP_LOCALIZACAO_ESC', 'TP_SIT_FUNC_ESC',
       'IN_BAIXA_VISAO', 'IN_CEGUEIRA', 'IN_SURDEZ',
       'IN_DEFICIENCIA_AUDITIVA', 'IN_SURDO_CEGUEIRA',
       'IN_DEFICIENCIA_FISICA', 'IN_DEFICIENCIA_MENTAL',
       'IN_DEFICIT_ATENCAO', 'IN_DISLEXIA', 'IN_DISCALCULIA',
       'IN_AUTISMO', 'IN_VISAO_MONOCULAR', 'IN_OUTRA_DEF', 'IN_GESTANTE',
       'IN_LACTANTE', 'IN_IDOSO', 'IN_ESTUDA_CLASSE_HOSPITALAR',
       'IN_SEM_RECURSO', 'IN_BRAILLE', 'IN_AMPLIADA_24', 'IN_AMPLIADA_18',
       'IN_LEDOR', 'IN_ACESSO', 'IN_TRANSCRICAO', 'IN_LIBRAS',
       'IN_TEMPO_ADICIONAL', 'IN_LEITURA_LABIAL', 'IN_MESA_CADEIRA_RODAS',
       'IN_MESA_CADEIRA_SEPARADA', 'IN_APOIO_PERNA', 'IN_GUIA_INTERPRETE',
       'IN_COMPUTADOR', 'IN_CADEIRA_ESPECIAL', 'IN_CADEIRA_CANHOTO',
       'IN_CADEIRA_ACOLCHOADA', 'IN_PROVA_DEITADO', 'IN_MOBILIARIO_OBESO',
       'IN_LAMINA_OVERLAY', 'IN_PROTETOR_AURICULAR', 'IN_MEDIDOR_GLICOSE',
       'IN_MAQUINA_BRAILE', 'IN_SOROBAN', 'IN_MARCA_PASSO', 'IN_SONDA',
       'IN_MEDICAMENTOS', 'IN_SALA_INDIVIDUAL', 'IN_SALA_ESPECIAL',
       'IN_SALA_ACOMPANHANTE', 'IN_MOBILIARIO_ESPECIFICO',
       'IN_MATERIAL_ESPECIFICO', 'IN_NOME_SOCIAL', 'CO_MUNICIPIO_PROVA',
       'NO_MUNICIPIO_PROVA', 'CO_UF_PROVA', 'SG_UF_PROVA',
       'TP_PRESENCA_CN', 'TP_PRESENCA_CH', 'TP_PRESENCA_LC',
       'TP_PRESENCA_MT', 'CO_PROVA_CN', 'CO_PROVA_CH', 'CO_PROVA_LC',
       'CO_PROVA_MT', 'NU_NOTA_CN', 'NU_NOTA_CH', 'NU_NOTA_LC',
       'NU_NOTA_MT', 'TX_RESPOSTAS_CN', 'TX_RESPOSTAS_CH',
       'TX_RESPOSTAS_LC', 'TX_RESPOSTAS_MT', 'TP_LINGUA',
       'TX_GABARITO_CN', 'TX_GABARITO_CH', 'TX_GABARITO_LC',
       'TX_GABARITO_MT', 'TP_STATUS_REDACAO', 'NU_NOTA_COMP1',
       'NU_NOTA_COMP2', 'NU_NOTA_COMP3', 'NU_NOTA_COMP4', 'NU_NOTA_COMP5',
       'NU_NOTA_REDACAO', 'Q001', 'Q002', 'Q003', 'Q004', 'Q005', 'Q006',
       'Q007', 'Q008', 'Q009', 'Q010', 'Q011', 'Q012', 'Q013', 'Q014',
       'Q015', 'Q016', 'Q017', 'Q018', 'Q019', 'Q020', 'Q021', 'Q022',
       'Q023', 'Q024', 'Q025'], dtype=object)

In [123]:
microdadosEnemSelecionado = microdadosEnem.filter(items = ['CO_MUNICIPIO_RESIDENCIA','NO_MUNICIPIO_RESIDENCIA',
                             'CO_UF_RESIDENCIA','SG_UF_RESIDENCIA','NU_NOTA_CN',
                             'NU_NOTA_CH','NU_NOTA_LC', 'NU_NOTA_MT','NU_NOTA_REDACAO'])

In [124]:
microdadosEnemSelecionado

,CO_MUNICIPIO_RESIDENCIA,NO_MUNICIPIO_RESIDENCIA,CO_UF_RESIDENCIA,SG_UF_RESIDENCIA,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO
0,3552205,Sorocaba,35,SP,NaN,NaN,NaN,NaN,NaN
1,2910800,Feira de Santana,29,BA,NaN,NaN,NaN,NaN,NaN
2,2304400,Fortaleza,23,CE,NaN,NaN,NaN,NaN,NaN
3,1721000,Palmas,17,TO,483.8,503.6,537.3,392.0,460.0
4,3118601,Contagem,31,MG,513.6,575.5,570.7,677.0,860.0
...,...,...,...,...,...,...,...,...,...
5095265,5300108,Brasília,53,DF,NaN,NaN,NaN,NaN,NaN
5095266,1302603,Manaus,13,AM,NaN,578.9,555.5,NaN,500.0
5095267,4302105,Bento Gonçalves,43,RS,NaN,NaN,NaN,NaN,NaN
5095268,4302105,Bento Gonçalves,43,RS,NaN,NaN,NaN,NaN,NaN
5095269,4302105,Bento Gonçalves,43,RS,NaN,NaN,NaN,NaN,NaN

In [127]:
mediaEnemPorMunicipio = microdadosEnemSelecionado.groupby(['CO_MUNICIPIO_RESIDENCIA',
                                                            'NO_MUNICIPIO_RESIDENCIA',
                                                            'CO_UF_RESIDENCIA',
                                                            'SG_UF_RESIDENCIA']).mean()

In [128]:
mediaEnemPorMunicipio

,,,,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO
CO_MUNICIPIO_RESIDENCIA,NO_MUNICIPIO_RESIDENCIA,CO_UF_RESIDENCIA,SG_UF_RESIDENCIA,,,,,
1100015,Alta Floresta D'Oeste,11,RO,466.877454,493.412214,504.998473,503.000000,555.776081
1100023,Ariquemes,11,RO,463.542845,489.960333,506.999802,498.971037,524.149147
1100031,Cabixi,11,RO,454.453125,474.152239,486.223881,497.443750,492.835821
1100049,Cacoal,11,RO,469.165657,494.664063,510.185132,510.684635,538.657074
1100056,Cerejeiras,11,RO,468.381164,488.456536,507.604902,505.175685,552.222222
...,...,...,...,...,...,...,...,...
5222005,Vianópolis,52,GO,467.945495,492.496537,512.282684,528.815315,563.896104
5222054,Vicentinópolis,52,GO,443.824194,469.941270,489.447619,504.204839,503.492063
5222203,Vila Boa,52,GO,433.489130,446.955102,469.622449,474.306522,465.714286
5222302,Vila Propício,52,GO,450.603636,464.472414,480.539655,474.847273,460.689655
5300108,Brasília,53,DF,492.786286,523.134671,535.237884,536.788562,585.451783

In [132]:
mediaEnemPorMunicipio = microdadosEnemSelecionado.groupby(['CO_MUNICIPIO_RESIDENCIA',
                                                            'NO_MUNICIPIO_RESIDENCIA',
                                                            'CO_UF_RESIDENCIA',
                                                            'SG_UF_RESIDENCIA']).mean()

In [133]:
mediaEnemPorMunicipio

,,,,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO
CO_MUNICIPIO_RESIDENCIA,NO_MUNICIPIO_RESIDENCIA,CO_UF_RESIDENCIA,SG_UF_RESIDENCIA,,,,,
1100015,Alta Floresta D'Oeste,11,RO,466.877454,493.412214,504.998473,503.000000,555.776081
1100023,Ariquemes,11,RO,463.542845,489.960333,506.999802,498.971037,524.149147
1100031,Cabixi,11,RO,454.453125,474.152239,486.223881,497.443750,492.835821
1100049,Cacoal,11,RO,469.165657,494.664063,510.185132,510.684635,538.657074
1100056,Cerejeiras,11,RO,468.381164,488.456536,507.604902,505.175685,552.222222
...,...,...,...,...,...,...,...,...
5222005,Vianópolis,52,GO,467.945495,492.496537,512.282684,528.815315,563.896104
5222054,Vicentinópolis,52,GO,443.824194,469.941270,489.447619,504.204839,503.492063
5222203,Vila Boa,52,GO,433.489130,446.955102,469.622449,474.306522,465.714286
5222302,Vila Propício,52,GO,450.603636,464.472414,480.539655,474.847273,460.689655
5300108,Brasília,53,DF,492.786286,523.134671,535.237884,536.788562,585.451783

In [134]:
mediaEnemPorMunicipio = microdadosEnemSelecionado\
.groupby(['CO_MUNICIPIO_RESIDENCIA',
        'NO_MUNICIPIO_RESIDENCIA',
        'CO_UF_RESIDENCIA',
        'SG_UF_RESIDENCIA'],as_index = False).mean()

In [135]:
mediaEnemPorMunicipio

,CO_MUNICIPIO_RESIDENCIA,NO_MUNICIPIO_RESIDENCIA,CO_UF_RESIDENCIA,SG_UF_RESIDENCIA,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO
0,1100015,Alta Floresta D'Oeste,11,RO,466.877454,493.412214,504.998473,503.000000,555.776081
1,1100023,Ariquemes,11,RO,463.542845,489.960333,506.999802,498.971037,524.149147
2,1100031,Cabixi,11,RO,454.453125,474.152239,486.223881,497.443750,492.835821
3,1100049,Cacoal,11,RO,469.165657,494.664063,510.185132,510.684635,538.657074
4,1100056,Cerejeiras,11,RO,468.381164,488.456536,507.604902,505.175685,552.222222
...,...,...,...,...,...,...,...,...,...
5565,5222005,Vianópolis,52,GO,467.945495,492.496537,512.282684,528.815315,563.896104
5566,5222054,Vicentinópolis,52,GO,443.824194,469.941270,489.447619,504.204839,503.492063
5567,5222203,Vila Boa,52,GO,433.489130,446.955102,469.622449,474.306522,465.714286
5568,5222302,Vila Propício,52,GO,450.603636,464.472414,480.539655,474.847273,460.689655
5569,5300108,Brasília,53,DF,492.786286,523.134671,535.237884,536.788562,585.451783

In [136]:
mediaEnemPorMunicipio.to_csv('MediaEnemPorMunicipio.csv')